spring:
  sql:
    init:
      mode: always
  datacourse:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL}
    username: ${USERNAME}
    password: ${PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000
