SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE orders_detail;
TRUNCATE TABLE cart_item;
TRUNCATE TABLE order;
TRUNCATE TABLE image;
TRUNCATE TABLE product;
TRUNCATE TABLE customer;
SET FOREIGN_KEY_CHECKS = 1;
